### ISSUE TITLE
DATA URL errors

### ISSUE THREAD

**Issue by OzgeUmut** [boun-tabi/NLI-TR#11]
While downloading nli datasets via load_dataset 
ConnectionError: Couldn't reach https://tabilab.cmpe.boun.edu.tr/datasets/nli_datasets/snli_tr_1.0.zip is given.
In the boun website it is states: "The requested page "/datasets/nli_datasets/snli_tr_1.0.zip" could not be found." Is there another way to accesss this dataset? Can this problem be fixed?

**Comment by e-budur** [comment]
Hi Ozge, 
Sorry to hear that you've experienced issue when downloading the dataset through `load_dataset`. We're working to resolve the issue. In the meantime, you can access the datasets through the updated links [here](https://github.com/boun-tabi/NLI-TR?tab=readme-ov-file#-download-nli-tr).
Thank you for your interest in `NLI-TR` dataset. Please feel free to reach out if you have any further question.
Regards,
Emrah

**Comment by e-budur** [comment]
You may keep track of [this pull request](https://huggingface.co/datasets/nli_tr/discussions/5) about fixing the links for `nli_tr` when accessed through the `load_dataset` function.

**Comment by OzgeUmut** [comment]
Thank you.
