### ISSUE TITLE
What is Prompt ID ?

### ISSUE THREAD

**Issue by ardofski** [boun-tabi/NLI-TR#8]
Thanks for your precious work !

In the example for SNLI and SNLI-TR, there is field called "promptID" but I couldn't see it in both SNLI dataset and SNLI-TR dataset. 
An example annotation from SNLI-TR is:
```
    {
        "annotator_labels": [
            "neutral",
            "contradiction",
            "contradiction",
            "neutral",
            "neutral"
        ],
        "captionID": "2677109430.jpg#1",
        "gold_label": "neutral",
        "pairID": "2677109430.jpg#1r1n",
        "sentence1": "Bu kilise korosu, kilisedeki kitaptan neşeli şarkılar söylerken kitlelere şarkı söyler.",
        "sentence2": "Kilisenin tavanında çatlaklar var."
    }
```

What is the meaning of this promptID in the README or is it just typo ?

Thanks

**Comment by e-budur** [comment]
Hi Arda (@ardofski) 
Thank you so much for your interest in the dataset and also for sharing this great finding.
Actually, `promptID`  refers to an internal identity field for the set of `premise`, `entailment`, `contradiction`, `neutral` sentences referring to the same image.  This field exists actually in MNLI 1.0 dataset but missing in SNLI1.0 dataset.  

We generated and used this field for our internal purposes while annotating the dataset.  But apparently, we forgot to remove it from the examples on the Readme page.  Just updated the Readme page accordingly.   You can safely ignore it

Thank you so much for pointing that out. Please feel free to reach out if you have any further questions.
Emrah
