### ISSUE TITLE
Error with your data URLs: Server Not Found

### ISSUE THREAD

**Issue by albertvillanova** [boun-tabi/NLI-TR#9]
When trying to access your data URLs, we find a Server Not Found error, e.g.: https://tabilab.cmpe.boun.edu.tr/datasets/nli_datasets/snli_tr_1.0.zip

**Comment by e-budur** [comment]
Thanks @albertvillanova.  The server went down temporarily for maintenance.  It should be working now.  Can you please check it once again?

We'll move the file to a more reliable medium and share the result under this issue.

**Comment by albertvillanova** [comment]
Thank you. The data files are accessible again.
